### ISSUE TITLE
User and Authentication 1.1

### ISSUE THREAD

**Issue by wyatt-herkamp** [wyatt-herkamp/nitro_repo#326]
# Tasks
- [x] Refactor Nitro_Repo to allow for different database types(SQLIte and Postgres) and to allow different user storage methods
- [x] Session Token Storages methods such as Redis and In-Memory
- [x] Complete Login Tokens #100

# Token Types
Session Tokens `nrs_{}` for sessions. 
1. Created upon first connection to website. Stored in Cookies
2. Stored in Memory or Redis
3.   Will reference the Authentication Token
4. 24 life time.
Authentication Token `nrp_{}`
1. Stored in Database
2. Life Span is specified upon creation. So 24 if for session token.  or even like 90 days if you are going to use this for like your deploying from Maven 
3. Can be sent with API requests instead of session tokens. For API stuff 
4. Will be an alternative for deploying using usernames and passwords

**Comment by wyatt-herkamp** [comment]
Completed in the 1.1 Dev Branch
